

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`ENDERECO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ENDERECO` (
  `ID_ENDERECO` INT NOT NULL AUTO_INCREMENT,
  `TIPO_DO_RESIDENTE` VARCHAR(15) NOT NULL,
  `RUA` VARCHAR(75) NOT NULL,
  `BAIRRO` VARCHAR(25) NOT NULL,
  `CIDADE` VARCHAR(50) NOT NULL,
  `ESTADO` VARCHAR(25) NOT NULL,
  `COMPLEMENTO` VARCHAR(100) NULL,
  PRIMARY KEY (`ID_ENDERECO`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`FUNCIONARIO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`FUNCIONARIO` (
  `ID_FUNCIONARIO` INT NOT NULL AUTO_INCREMENT,
  `ID_ENDERECO` INT NOT NULL,
  `ID_SUPERVISOR` INT NULL,
  `CARGO` VARCHAR(60) NOT NULL,
  `IDADE` INT NOT NULL,
  `CPF` VARCHAR(11) NOT NULL,
  `TURNO` VARCHAR(15) NOT NULL,
  `NOME` VARCHAR(70) NOT NULL,
  `SEXO` VARCHAR(1) NOT NULL,
  PRIMARY KEY (`ID_FUNCIONARIO`),
  INDEX `SUPERVISIONA_idx` (`ID_SUPERVISOR` ASC) VISIBLE,
  INDEX `fk_FUNCIONARIO_ENDERECO1_idx` (`ID_ENDERECO` ASC) VISIBLE,
  CONSTRAINT `SUPERVISIONA`
    FOREIGN KEY (`ID_SUPERVISOR`)
    REFERENCES `mydb`.`FUNCIONARIO` (`ID_FUNCIONARIO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_FUNCIONARIO_ENDERECO1`
    FOREIGN KEY (`ID_ENDERECO`)
    REFERENCES `mydb`.`ENDERECO` (`ID_ENDERECO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`MAQUINA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`MAQUINA` (
  `ID_MAQUINA` INT NOT NULL AUTO_INCREMENT,
  `MODELO` VARCHAR(30) NOT NULL,
  `MARCA` VARCHAR(30) NOT NULL,
  `ALOCADO` BIT NOT NULL,
  `STATUS` VARCHAR(20) NOT NULL,
  `TIPO_DE_CORTE` VARCHAR(25) NOT NULL,
  PRIMARY KEY (`ID_MAQUINA`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`FORNECEDOR`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`FORNECEDOR` (
  `ID_FORNECEDOR` INT NOT NULL AUTO_INCREMENT,
  `NOME_DO_FORNECEDOR` VARCHAR(85) NOT NULL,
  `TELEFONE_DO_FORNECEDOR` VARCHAR(11) NOT NULL,
  `CNPJ` VARCHAR(14) NOT NULL,
  PRIMARY KEY (`ID_FORNECEDOR`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`MANUTENCAO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`MANUTENCAO` (
  `ID_MANUTENCAO` INT NOT NULL AUTO_INCREMENT,
  `ID_MAQUINA` INT NOT NULL,
  `ID_FORNECEDOR` INT NOT NULL,
  `ID_FUNCIONARIO` INT NOT NULL,
  `STATUS` VARCHAR(20) NOT NULL,
  `VALOR` VARCHAR(10) NOT NULL,
  `DATA_INICIO` VARCHAR(45) NOT NULL,
  `DATA_FIM` DATETIME NULL,
  PRIMARY KEY (`ID_MANUTENCAO`),
  INDEX `MONITORA_idx` (`ID_FUNCIONARIO` ASC) VISIBLE,
  INDEX `ARRUMA_idx` (`ID_MAQUINA` ASC) VISIBLE,
  INDEX `fk_MANUTENCAO_FORNECEDOR1_idx` (`ID_FORNECEDOR` ASC) VISIBLE,
  CONSTRAINT `MONITORA`
    FOREIGN KEY (`ID_FUNCIONARIO`)
    REFERENCES `mydb`.`FUNCIONARIO` (`ID_FUNCIONARIO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `ARRUMA`
    FOREIGN KEY (`ID_MAQUINA`)
    REFERENCES `mydb`.`MAQUINA` (`ID_MAQUINA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_MANUTENCAO_FORNECEDOR1`
    FOREIGN KEY (`ID_FORNECEDOR`)
    REFERENCES `mydb`.`FORNECEDOR` (`ID_FORNECEDOR`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`HABILITACAO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`HABILITACAO` (
  `ID_HABILITACAO` INT NOT NULL,
  `ID_MAQUINA` INT NOT NULL,
  `TITULO` VARCHAR(30) NOT NULL,
  `NUMERO_DO_DOCUMENTO` VARCHAR(20) NOT NULL,
  `ANO_EXPEDICAO` INT NOT NULL,
  PRIMARY KEY (`ID_HABILITACAO`),
  INDEX `HABILITADO_idx` (`ID_MAQUINA` ASC) VISIBLE,
  CONSTRAINT `HABILITADO`
    FOREIGN KEY (`ID_MAQUINA`)
    REFERENCES `mydb`.`MAQUINA` (`ID_MAQUINA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CLIENTE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`CLIENTE` (
  `ID_CLIENTE` INT NOT NULL AUTO_INCREMENT,
  `CPF/CNPJ` VARCHAR(14) NOT NULL,
  `CHAVE_PIX` VARCHAR(80) NOT NULL,
  `IDADE` INT NOT NULL,
  `TELEFONE` VARCHAR(11) NOT NULL,
  `NOME` VARCHAR(45) NOT NULL,
  `EMAIL` VARCHAR(45) NOT NULL,
  `SEXO` VARCHAR(1) NOT NULL,
  PRIMARY KEY (`ID_CLIENTE`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`VENDA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`VENDA` (
  `ID_VENDA` INT NOT NULL,
  `ID_ENDERECO` INT NOT NULL,
  `ID_FUNCIONARIO` INT NOT NULL,
  `ID_CLIENTE` INT NOT NULL,
  `NUMERO_NF` VARCHAR(30) NOT NULL,
  `DATA_DA_VENDA` DATETIME NOT NULL,
  `VALOR_VENDA` VARCHAR(10) NOT NULL,
  `PORCENTAGEM_DE_DESCONTO` DECIMAL(4,2) NOT NULL,
  PRIMARY KEY (`ID_VENDA`),
  INDEX `ENTREGA_idx` (`ID_ENDERECO` ASC) VISIBLE,
  INDEX `fk_VENDA_CLIENTE1_idx` (`ID_CLIENTE` ASC) VISIBLE,
  INDEX `fk_VENDA_FUNCIONARIO1_idx` (`ID_FUNCIONARIO` ASC) VISIBLE,
  CONSTRAINT `ENTREGA`
    FOREIGN KEY (`ID_ENDERECO`)
    REFERENCES `mydb`.`ENDERECO` (`ID_ENDERECO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_VENDA_CLIENTE1`
    FOREIGN KEY (`ID_CLIENTE`)
    REFERENCES `mydb`.`CLIENTE` (`ID_CLIENTE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_VENDA_FUNCIONARIO1`
    FOREIGN KEY (`ID_FUNCIONARIO`)
    REFERENCES `mydb`.`FUNCIONARIO` (`ID_FUNCIONARIO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ESTILISTA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ESTILISTA` (
  `ID_ESTILISTA` INT NOT NULL AUTO_INCREMENT,
  `ID_ENDERECO` INT NOT NULL,
  `NOME` VARCHAR(70) NOT NULL,
  `CPF/CNPJ` VARCHAR(14) NOT NULL,
  `ESPECIALIDADE` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`ID_ESTILISTA`),
  INDEX `LOCALIZADO_idx` (`ID_ENDERECO` ASC) VISIBLE,
  CONSTRAINT `LOCALIZADO`
    FOREIGN KEY (`ID_ENDERECO`)
    REFERENCES `mydb`.`ENDERECO` (`ID_ENDERECO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ROUPA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ROUPA` (
  `ID_ROUPA` INT NOT NULL AUTO_INCREMENT,
  `ID_ESTILISTA` INT NOT NULL,
  `TAMANHO` VARCHAR(3) NOT NULL,
  `TECIDO` VARCHAR(35) NOT NULL,
  `COR` VARCHAR(15) NOT NULL,
  `MODELO` VARCHAR(20) NOT NULL,
  `FOTO_ROUPA` BLOB NULL,
  PRIMARY KEY (`ID_ROUPA`),
  INDEX `CRIADO_idx` (`ID_ESTILISTA` ASC) VISIBLE,
  CONSTRAINT `CRIADO`
    FOREIGN KEY (`ID_ESTILISTA`)
    REFERENCES `mydb`.`ESTILISTA` (`ID_ESTILISTA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ENDERECO_CLIENTE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ENDERECO_CLIENTE` (
  `ID_ENDERECO_CLIENTE` INT NOT NULL,
  `ID_ENDERECO` INT NOT NULL,
  `ID_CLIENTE` INT NOT NULL,
  PRIMARY KEY (`ID_ENDERECO_CLIENTE`),
  INDEX `FK_CLIENTE_idx` (`ID_CLIENTE` ASC) VISIBLE,
  INDEX `FK_ENDERECO_idx` (`ID_ENDERECO` ASC) VISIBLE,
  CONSTRAINT `FK_CLIENTE`
    FOREIGN KEY (`ID_CLIENTE`)
    REFERENCES `mydb`.`CLIENTE` (`ID_CLIENTE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_ENDERECO`
    FOREIGN KEY (`ID_ENDERECO`)
    REFERENCES `mydb`.`ENDERECO` (`ID_ENDERECO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PRODUCAO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PRODUCAO` (
  `ID_PRODUCAO` INT NOT NULL,
  `ID_SUPERVISOR` INT NOT NULL,
  `ID_FUNCIONARIO` INT NOT NULL,
  `ID_MAQUINA` INT NOT NULL,
  `ID_ROUPA` INT NOT NULL,
  `OBS_PRODUCAO` VARCHAR(200) NOT NULL,
  `DATA_FABRICACAO` DATETIME NOT NULL,
  `STATUS` VARCHAR(25) NOT NULL,
  PRIMARY KEY (`ID_PRODUCAO`),
  INDEX `FK_SUPERVISOR_idx` (`ID_SUPERVISOR` ASC) VISIBLE,
  INDEX `FK_FUNCIONARIO_idx` (`ID_FUNCIONARIO` ASC) VISIBLE,
  INDEX `FK_MAQUINA_idx` (`ID_MAQUINA` ASC) VISIBLE,
  INDEX `fk_PRODUCAO_ROUPA1_idx` (`ID_ROUPA` ASC) VISIBLE,
  CONSTRAINT `FK_SUPERVISOR`
    FOREIGN KEY (`ID_SUPERVISOR`)
    REFERENCES `mydb`.`FUNCIONARIO` (`ID_FUNCIONARIO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_FUNCIONARIO`
    FOREIGN KEY (`ID_FUNCIONARIO`)
    REFERENCES `mydb`.`FUNCIONARIO` (`ID_FUNCIONARIO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_MAQUINA`
    FOREIGN KEY (`ID_MAQUINA`)
    REFERENCES `mydb`.`MAQUINA` (`ID_MAQUINA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PRODUCAO_ROUPA1`
    FOREIGN KEY (`ID_ROUPA`)
    REFERENCES `mydb`.`ROUPA` (`ID_ROUPA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ROUPA_VENDA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ROUPA_VENDA` (
  `ROUPA_ID_ROUPA` INT NOT NULL,
  `VENDA_ID_VENDA` INT NOT NULL,
  `QNTD_VENDIDA` INT NOT NULL,
  `VALOR_VENDA` VARCHAR(10) GENERATED ALWAYS AS () VIRTUAL,
  PRIMARY KEY (`ROUPA_ID_ROUPA`, `VENDA_ID_VENDA`),
  INDEX `fk_ROUPA_has_VENDA_VENDA1_idx` (`VENDA_ID_VENDA` ASC) VISIBLE,
  INDEX `fk_ROUPA_has_VENDA_ROUPA1_idx` (`ROUPA_ID_ROUPA` ASC) VISIBLE,
  CONSTRAINT `fk_ROUPA_has_VENDA_ROUPA1`
    FOREIGN KEY (`ROUPA_ID_ROUPA`)
    REFERENCES `mydb`.`ROUPA` (`ID_ROUPA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ROUPA_has_VENDA_VENDA1`
    FOREIGN KEY (`VENDA_ID_VENDA`)
    REFERENCES `mydb`.`VENDA` (`ID_VENDA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`FUNCIONARIO_HABILITACAO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`FUNCIONARIO_HABILITACAO` (
  `FUNCIONARIO_ID_FUNCIONARIO` INT NOT NULL,
  `HABILITACAO_ID_HABILITACAO` INT NOT NULL,
  PRIMARY KEY (`FUNCIONARIO_ID_FUNCIONARIO`, `HABILITACAO_ID_HABILITACAO`),
  INDEX `fk_FUNCIONARIO_has_HABILITACAO_HABILITACAO1_idx` (`HABILITACAO_ID_HABILITACAO` ASC) VISIBLE,
  INDEX `fk_FUNCIONARIO_has_HABILITACAO_FUNCIONARIO1_idx` (`FUNCIONARIO_ID_FUNCIONARIO` ASC) VISIBLE,
  CONSTRAINT `fk_FUNCIONARIO_has_HABILITACAO_FUNCIONARIO1`
    FOREIGN KEY (`FUNCIONARIO_ID_FUNCIONARIO`)
    REFERENCES `mydb`.`FUNCIONARIO` (`ID_FUNCIONARIO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_FUNCIONARIO_has_HABILITACAO_HABILITACAO1`
    FOREIGN KEY (`HABILITACAO_ID_HABILITACAO`)
    REFERENCES `mydb`.`HABILITACAO` (`ID_HABILITACAO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
